### ISSUE TITLE
ac-15-16.jpg

### ISSUE THREAD

**Issue by rajatsaxena035** [opengbu/gbuonline#1]
![ac-15-16](https://cloud.githubusercontent.com/assets/12662477/8393516/793c7ee2-1d30-11e5-9f7c-c3f7275bbaaf.jpg)

**Comment by Varun-garg** [comment]
So we use this as new calander or update our existing one?
If we are going to update our existing one, (which looks very clean), we can watermark it with gbuonline.in .
Any ideas?

**Comment by gargsarthak30** [comment]
Although editing the current version of our calendar would be time consuming but that calendar really looks pretty cool as compared to this scanned copy. So I think we'll edit that one and put our watermark over there.

-----Original Message-----

**Comment by awasthi** [comment]
Yes sure we should mark it.

**Comment by rajatsaxena035** [comment]
I think we should replace our existing "academic calendar"(AC)  with this one because :

<hr>

<ol>
<li>Although the existing AC is more tidy, <b>it is highly susceptible to errors,</b> bec. we need to wriite it in .docx and then convert to .pdf or .jpg.. And this process will have to be done each year.</li>
<hr>
<li>The new AC is the one which the "Admin"  uploads each year on <a href="http://www.gbu.ac.in"> www.gbu.ac.in </a>.<b> Therefore, the users will find it more reliable and authentic.</b></li> 
 <hr>
<li>But we will surely think of ways to improve its look.
<ul>
<li>rotating it by some angle towards left.</li>
<li> giving it a border </li>
</ul> 
</li>
</ol>

<hr>

To put in short, I think we should not interfere with its text. Styling it, is good enough.

**Comment by gargsarthak30** [comment]
Guys check the footer now. I have made some changes to it , hope you'll
like it !!!

**Comment by Varun-garg** [comment]
sweet footer.
