### ISSUE TITLE
redundant work.

### ISSUE THREAD

**Issue by bhaweshchandola** [opengbu/gbuonline#10]
i noticed in most of the pages that you've written the code more than it is required like:
![capture](https://cloud.githubusercontent.com/assets/12662679/8510712/541b71a6-2314-11e5-873e-ac6312287b86.JPG)
(i am not pointing out this one in particular). 
now the thing is rather than writing this part again and again. you should construct a loop which will work until there is data available in database.

**Comment by Varun-garg** [comment]
Agreed, placing the same code 3-4 times makes it difficult to spot and erase the duplicate work with all the html formatting, and change it back to single with loops. The loops should have been constructed the first time and run like 3-4 times depending upon intended purpose.

**Comment by bhaweshchandola** [comment]
yes varun is absolutely right. so to explain to how it will be done i have worked a prototype.
![capture1](https://cloud.githubusercontent.com/assets/12662679/8512499/0528824c-2363-11e5-94c0-15c1cfd9a73f.JPG)
just take a look at this and work accordingly.
