### ISSUE TITLE
New Background Cover

### ISSUE THREAD

**Issue by Shobhit95Sharma** [opengbu/gbuonline#12]
Just found a new background cover.
We'll have to change the color of text of every page but it looks good to me.

![back1](https://cloud.githubusercontent.com/assets/9257782/8602041/a64ff59c-268d-11e5-9805-9d00f04f430b.PNG)
![back2](https://cloud.githubusercontent.com/assets/9257782/8602054/afdc16ea-268d-11e5-8832-795f796fbd04.PNG)

**Comment by rajatsaxena035** [comment]
It looks good for the homepage, but i think for internal pages, it would be quite dark.
