### ISSUE TITLE
Front Page Update

### ISSUE THREAD

**Issue by Varun-garg** [opengbu/gbuonline#15]
Hi
I was wondering if we can improve first page by
1. Adding some space b/w navbar and top of page, where we can post our site logo and site info links
2. Add date icon in events, news and notices
3. Slider improvement /change
4. Auto scroll in news

The front page should look like this
http://www.nscsindia.org/
(Recommended By Awasthi Sir)

**Comment by gargsarthak30** [comment]
Front page has been updated.
If you want anything to be updated on front page, just ping me.

-----Original Message-----

**Comment by Varun-garg** [comment]
Just wondering why have you kept single image in slider?

-----Original Message-----

Date: Wed, 15 Jul 2015 09:09:13 -0700
