### ISSUE TITLE
(Front end) header.php switch title

### ISSUE THREAD

**Issue by Varun-garg** [opengbu/gbuonline#2]
In all pages, we have same title Welcome to gbu online. I think the title should be for front page only. For other pages, we should switch it according to the controller calling it.

**Comment by rajatsaxena035** [comment]
Yes, we will do it in a day or two.
Thanks for reminding.

**Comment by gargsarthak30** [comment]
Hey Everyone!!!
Send me your Linkedin profile links and your email addresses for the
"Contact Us" tab in footer.

**Comment by Varun-garg** [comment]
check your email.

**Comment by bhaweshchandola** [comment]
https://www.linkedin.com/profile/view?id=285854398&trk=nav_responsive_tab_profile_pic
bhawesh.chandola@gmail.com

**Comment by Shobhit95Sharma** [comment]
https://www.linkedin.com/profile/view?id=285566479&trk=nav_responsive_tab_profile
shobhit95sharma@gmail.com
