### ISSUE TITLE
Footer issues

### ISSUE THREAD

**Issue by Varun-garg** [opengbu/gbuonline#21]
## Issue 1

In cases when document height is less than window height footer is dragged in middle. Can someone fix it ?

![screenshot from 2015-07-20 23-40-07](https://cloud.githubusercontent.com/assets/5960246/8783440/61d1a3b2-2f0b-11e5-9dfb-d9a7cccce184.png)
## Issue 2

The disqus section is cool but it would be better if it is not in footer of each page (It slows down site). We can set a php variable to true in page we need comments and check it in footer. If true we can load the disqus code.

**Comment by rajatsaxena035** [comment]
I will try to fix these issues in few hours.

**Comment by rajatsaxena035** [comment]
Issue 1 : Solved<br>
<b>Earlier : </b><br>
![fi](https://cloud.githubusercontent.com/assets/12662477/8793278/0ea986dc-2f92-11e5-9939-0336dfc74f3f.png)
<hr><b>Now :</b><br>
![footer_solved](https://cloud.githubusercontent.com/assets/12662477/8793277/0ea12c6c-2f92-11e5-942f-02cc83ba0bb5.png)

**Comment by kshitijpurwar** [comment]
hey guys,noticed you were using notepad++,would be much more productive if you use sublime text with emmet.In case you need a web developer  with javascript knowledge,contact me.
email id: kshitij.purwar4@gmail.com .

**Comment by awasthi** [comment]
Kshitiz! Are you gbu student. If yes you may contact me at sovsas v215.

**Comment by rajatsaxena035** [comment]
Footer-Issue 2 : Solved
