### ISSUE TITLE
Faculty Section

### ISSUE THREAD

**Issue by rajatsaxena035** [opengbu/gbuonline#22]
@Varun-garg 
Need your help regarding faculty details. 
Meet me as soon as possible.

**Comment by Varun-garg** [comment]
Sorry, I was not in my room, are you awake now?

**Comment by rajatsaxena035** [comment]
@Varun-garg 
Please come to SOVSAS as soon as possible.

**Comment by Varun-garg** [comment]
Sorry, I was in messs, and you are back in your room (probably sleeping). Call me when you read this.
