### ISSUE TITLE
Question about hits counter

### ISSUE THREAD

**Issue by Varun-garg** [opengbu/gbuonline#23]
Hi, I saw hit counter added on front page and displayed in admin panel. It is nice, however the code is

```
$hit=$this->db->query("select max(hits) as maxhit from analysis");
$results=$hit->result();
$date = date('Y-m-d '); 
$time = date('H:i:s');

foreach($results as $rows)
{
    $updatehits = $rows->maxhit;
    $updatehits+=1;

}

$storehits=$this->db->query("insert into analysis values ('$date','$time','$updatehits')");
```

I thought it would be a simple increment, but incremented value is inserted each time with current date and time. Date and time can be good for statistics but then
1. If we only need total count, a simple increment would have been better.
2. If the statistics are displayed by each day, then there is no need of time and hits should be of that day and not total hits
3. If we are inserting both date and time, in our table it means first row has hits 1, second has hits 2 and so on. There is no need to find the maximum value and then increment it. In-fact we don't need hits column in this case. The number of hits around a time can be found by counting the rows around that time, and total hits at that time can be accessed by counting number of rows upto that record.

(If we see the db max(hits) is only total rows)

**Comment by rajatsaxena035** [comment]
@Varun-garg 
Point 3 : You are absolutely correct. I will correct this in few minutes.
Point 2 : We need "time" to analyse at what time traffic on our website is max on a particular day.
              Moreover if someone repeatedly presses F5 to increase the "hits", we can easily                  analyze this.
