### ISSUE TITLE
Database Import - Blog Table 

### ISSUE THREAD

**Issue by rajatsaxena035** [opengbu/gbuonline#3]
![db_import](https://cloud.githubusercontent.com/assets/12662477/8464099/5ff9ac5e-205d-11e5-8183-a9eb30cb47c7.png)

**Comment by awasthi** [comment]
I suggest one more important feature related with database. Table name
should be dynamic. I mean end should be able to rename table names. not
full name of table but he should be able to add some prefix like ab_ etc.

**Comment by Varun-garg** [comment]
@rajatsaxena035 I will look into this shortly.

@awasthi Sir we will make an installer then.

**Comment by Varun-garg** [comment]
@rajatsaxena035 It clearly says no database selected. First create a database 'gbuonline'  (which you have dropped instead of just dropping the tabes ) and then click on it (select) then go to import and then import it (gbuonline.sql).

**Comment by Varun-garg** [comment]
Many of us here have code which is different on github. To see what is actually on I have uploaded a temporary copy of our site to http://tech-league.me/ .I will remove it as soon as work is finished.

**Comment by rajatsaxena035** [comment]
@Varun-garg  Thanks.....and the new admin panel is just excellent.

**Comment by Varun-garg** [comment]
@rajatsaxena035 Glad you liked it :smile:
