### ISSUE TITLE
Rare access denied issue.

### ISSUE THREAD

**Issue by Varun-garg** [opengbu/gbuonline#30]
This is mainly in users, directory that a access denied message is displayed, which works again on refresh

This is a issue that is bothering me for long, and I not able to find a solution.
Few other instances - 

http://multimerch.com/blog/solving-nginx-php-fpm-access-denied-issue/
http://wiki.e107.org/index.php?title=I_see_a_White_Page_which_says_Access_Denied

**Comment by Varun-garg** [comment]
Today I saw this on other pages too. We need to fix this

**Comment by awasthi** [comment]
Let know the page where it occurs.

On 1 October 2015 at 05:13, Varun Garg notifications@github.com wrote:

> Today I saw this on other pages too. We need to fix this
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/opengbu/gbuonline/issues/30#issuecomment-144575644.

## 

अमित अवस्थी
व्यवसायिक अध्ययन एवम्  अनुप्रयुक्त विज्ञान विद्यालय
गौतम बुध विश्वविद्यालय
ग्रेटर नोइडा-201308, उत्तर प्रदेश , भारत

Amit K Awasthi
Group For Cryptology Reserarch
School of Voc Studies and Applied Sciences
Gautam Buddha University,

## Greater Noida-201308, UP, INDIA

ResearcherID::    http://www.researcherid.com/rid/D-3118-2014
ORCID::                 http://orcid.org/0000-0002-5500-0361
SCOPUS ID:
http://www.scopus.com/authid/detail.url?authorId=7006541429
