### ISSUE TITLE
GBU Online phase - III‏ 

### ISSUE THREAD

**Issue by Varun-garg** [opengbu/gbuonline#31]
Since we did not have a team meeting for long time, I am leaving this here

**Comment by Varun-garg** [comment]
During vacations we started building up gbuonline form a new start. I think it is time we should do it again...

**New things that I would like to add**
-with existing news and updates we should pull them directly from GBU website, using JS, allowing us to add only items not in gbu website.
-section for results should be included, we can ask schools to give data, or use images
-press report should be also be loaded from gbu.ac.in
-Android app (I am going to start it soon)

**Things that need to be fixed completely**
-exam papers, ebooks etc
-front page - looks too static, and also image is too big. UX is bad.
-contributors page - missing images should not be displayed broken, they should not be displayed or be displayed with default image.

**Things that need very little improvement**
-Blogs, quick links etc
-Hostels (I cant be sure)
-Users (the only thing is left is separate upload for each section, other suggestions are open)....

**Things that should be removed**
-technological updates.

**Team issues**
Bhawesh Chandola -
Almost no work, only interested in creating databases and linking them with front end, which everyone can do on his own now. Not interested in PHP.

Sarthak Garg -
1) poor/very bad work quality - I had to go and fix lots of code myself.
2) Took a long time and a offensive language when I suggested navbar changes, then applied them silently one month later.
3) moved exams to google drive - I had to recode it and upload and relink all papers on my own.
4) Created a backdoor access for himself to check who is in contributors page
5) All pages that need to be fixed completely are under him.

We can dissolve bhawesh's role and assign sarthak's role to someone else. They will be a part of team but will be given really minor tasks. I think we can give rishabh, or new comers these tasks. Front page will be made by me and rajat.

**Design / Structure updates**
-Now that we know bootstrap well, we feel it a bit limited. We should use more libraries
-We can shift to Laravel framework, it is a bit tough to start with, but later it can be beneficial.

**Comment by bhaweshchandola** [comment]
Dear "Technical head" the reason you are not seeing any work from my side is because its done(i think you should focus on your work rather than interfering with others) and when the team started everyone was assigned the work upon their interest and i did the same, So talking about everyone able to do the database work on their own, well guess what everyone is capable enough to do everyone else's work(even yours). 
Yeah i get it you are the technical head so you think there is a need to boss around well let me tell you something as being the "Technical head" you should be giving us directions for our work, we are your team mates not your ___ slaves.

and you know what your post should actually go like this...

<b>Things that should be removed</b>
you(Varun Garg) as the technical head

<b>Team issues</b>
technical head's obsession and misuse of power . 

and as for the above blank use your imagination.

"You either die a hero or live long enough to see yourself become the villain"

**Comment by gargsarthak30** [comment]
Thank You Varun for your views. I have never replied to such issues in past, but now I think its high time and I need to tell you something.
<b>I think its the biggest mistake of team GBUONLINE to choose you as our "Technical Head".</b> Although other team members have never said you anything 
but I think I should tell you that none of us from the team is actually happy with you nature and your attitude. Just after you have been titled as the head, I don't know 
why but your nature has degraded drastically.
<b>The team has seen many instances, whenever someone tries to update something without asking you, you feel kind of insecure. You talk about "powers", Haah!!! </b>
You are not a part of a political team Man!! , where you want powers , we are just working together on a project but now I think working with you in a team 
,has actually been the worst experience. 
It seems like you are the only contributor to the site. For your kind information I have been giving my 100% to the site from the first day itself 
and now at this point when we have given our 4-5 months on this thing ,I cannot see such comments on my work.
Its good that you have the highest number of commits , but that doesn't mean you won't value some other person's effort.

<b>You have problem with the content team, internal members of the tech team and god knows who else. </b>
Coming on the the flaws that you have pointed out : 
- You never asked me to change the navbar. I don't know why you have pointed out this thing which actually never happened.
- Coming on to the exams part, you yourself said to upload the papers on google drive so as to lower down the load at server, 
  and then when I updated accordingly you tell us to put it on our server itself. (If you don't believe on this you may ask Rajat about this thing.)
- Backdoor access : Man, Three of us (Me , Bhawesh and Rajat) had made changes to the contributors page, but we didn't added authentication part just because 
  you were actually responsible for that thing. We even came to your room thrice , but unfortunately your room was found locked, we called you but you cared 
  enough of picking up the call. I have never asked for any backdoor access , never been fond of "POWERS" like you. Working just to enhance my skills and learn something.

One last thing, If you are working in a team then please have the etiquettes to talk directly to that person first rather than making an issue and posting it. 
It was actually a great experience working with you. I hope from now onwards I would take care that I don't work under such "Technical Head" ......

Regards
<b>SARTHAK GARG
(Contributor to GBUONLINE Now and Ever)  </b>

**Comment by Varun-garg** [comment]
> Dear "Technical head" the reason you are not seeing any work from my side is because its done(i think you should focus on your work rather than interfering with others) and when the team started everyone was assigned the work upon their interest and i did the same, So talking about everyone able to do the database work on their own, well guess what everyone is capable enough to do everyone else's work(even yours).

Dear Bhawesh, I remember correctly correctly you were given the task of handling databases on whole site. 

1. Though it was very small work, if you a bit serious about it, I wouldn't have been bothered at all. It was taking so long for you to do it I had to implement it in /users on my own which does more db operations that the rest of the site combined.

2. The connectivity that you did for schools was really redundant. For instance in schools, you just made a 3-4 line function and then did played copy and paste game. First you had this less work then you don't even do it properly is something that is not acceptable. And yeah the only insert operation that you did on site was - blogs that lacked basic validation (https://github.com/opengbu/gbuonline/blob/32cdcca8221de1023e97ba081a7872b0f9f70fb9/application/models/Blog_model.php)

3. Even this small work you did not complete. I had to to go and do lots of connectivity (compared to you specially) on the front end myself.

4. And the work that you did was very wrong, almost of all tables that you made I had to fix them. Then I had patch them here and also patch the front end. Sometimes I used to feel that it would been better if they did not exist in the first case.

> Yeah i get it you are the technical head so you think there is a need to boss around well let me tell you something as being the "Technical head" you should be giving us directions for our work, we are your team mates not your ___ slaves.

 ""directions for **our work**" - that is what I am trying to do. Work is something you (bhawesh) of all people should not speak off. Not only your work was little, you even failed to complete it. **I asked you several times to take some REAL work, but you always wanted to stick with the WORK that best suits your laziness**

>Things that should be removed
> you(Varun Garg) as the technical head
Alright, I am listening....so that's all the reason?

You think I am only one who is compaining? Your new partner sarthak used to say  same thing and used to tell me to give you content work since according to him you were doing nothing. When someone asks about your contribution he laughs about it. At least I do not believe in doing things such as behind someone's back. If I have issues I report them in front.  Even Amit Sir Asked me a few days ago ...**"kaun hai ye bhawesh, kuch kaam bhi karta hai vo"?**, and I was speechless with **kuch kaam**

> Team issues
> technical head's obsession and misuse of power .
Hmmm....That is coming from a guy who is almost removed from his "work".... The work that "existed" virtually. 

> and as for the above blank use your imagination.
> "You either die a hero or live long enough to see yourself become the villain"

I had the courtesy of asking you to do something and assigning you something, but you on the other hand can't control your emotions. If I did not knew you personally this would have happened a lot sooner. I knew sarthak but I did not expect such a reply from you at all.  Now that you have asked for it, I will wait to see the result and I have confidence on my dedication, so you are the one who should be afraid of the result.

I am dividing Technical team in 2 parts - Core and Extras. Extras will be you and Sarthak, and core will be rest. The extras will be a part of the team but not on GITHUB. They can submit their code using pull requests where it will be reviewed and then accepted. The reason you are not in the core is because to prevent you from entering core conversations which are only meant for those who do work. Also since your work will be like one pull request per month which is what guest collaborators do, it suits you best.

**Comment by Varun-garg** [comment]
> Dear "Technical head" the reason you are not seeing any work from my side is because its done(i think you should focus on your work rather than interfering with others) and when the team started everyone was assigned the work upon their interest and i did the same, So talking about everyone able to do the database work on their own, well guess what everyone is capable enough to do everyone else's work(even yours).

Dear Bhawesh, I remember correctly correctly you were given the task of handling databases on whole site. 

1. Though it was very small work, if you a bit serious about it, I wouldn't have been bothered at all. It was taking so long for you to do it I had to implement it in /users on my own which does more db operations that the rest of the site combined.

2. The connectivity that you did for schools was really redundant. For instance in schools, you just made a 3-4 line function and then did played copy and paste game. First you had this less work then you don't even do it properly is something that is not acceptable. And yeah the only insert operation that you did on site was - blogs that lacked basic validation (https://github.com/opengbu/gbuonline/blob/32cdcca8221de1023e97ba081a7872b0f9f70fb9/application/models/Blog_model.php)

3. Even this small work you did not complete. I had to to go and do lots of connectivity (compared to you specially) on the front end myself.

4. And the work that you did was very wrong, almost of all tables that you made I had to fix them. Then I had patch them here and also patch the front end. Sometimes I used to feel that it would been better if they did not exist in the first case.

> Yeah i get it you are the technical head so you think there is a need to boss around well let me tell you something as being the "Technical head" you should be giving us directions for our work, we are your team mates not your ___ slaves.

 ""directions for **our work**" - that is what I am trying to do. Work is something you (bhawesh) of all people should not speak off. Not only your work was little, you even failed to complete it. **I asked you several times to take some REAL work, but you always wanted to stick with the WORK that best suits your laziness**

>Things that should be removed
> you(Varun Garg) as the technical head

Alright, I am listening....so that's all the reason?
You think I am only one who is compaining? Your new partner sarthak used to say  same thing and used to tell me to give you content work since according to him you were doing nothing. When someone asks about your contribution he laughs about it. At least I do not believe in doing things such as behind someone's back. If I have issues I report them in front.  Even Amit Sir Asked me a few days ago ...**"kaun hai ye bhawesh, kuch kaam bhi karta hai vo"?**, and I was speechless with **kuch kaam**

> Team issues
> technical head's obsession and misuse of power .

Hmmm....That is coming from a guy who is almost removed from his "work".... The work that "existed" virtually. 

> and as for the above blank use your imagination.
> "You either die a hero or live long enough to see yourself become the villain"

I had the courtesy of asking you to do something and assigning you something, but you on the other hand can't control your emotions. If I did not knew you personally this would have happened a lot sooner. I knew sarthak but I did not expect such a reply from you at all.  Now that you have asked for it, I will wait to see the result and I have confidence on my dedication, so you are the one who should be afraid of the result.

I am dividing Technical team in 2 parts - Core and Extras. Extras will be you and Sarthak, and core will be rest. The extras will be a part of the team but not on GITHUB. They can submit their code using pull requests where it will be reviewed and then accepted. The reason you are not in the core is because to prevent you from entering core conversations which are only meant for those who do work. Also since your work will be like one pull request per month which is what guest collaborators do, it suits you best.

**Comment by Varun-garg** [comment]
> Dear "Technical head" the reason you are not seeing any work from my side is because its done(i think you should focus on your work rather than interfering with others) and when the team started everyone was assigned the work upon their interest and i did the same, So talking about everyone able to do the database work on their own, well guess what everyone is capable enough to do everyone else's work(even yours).

Dear Bhawesh, I remember correctly correctly you were given the task of handling databases on whole site. 

1. Though it was very small work, if you a bit serious about it, I wouldn't have been bothered at all. It was taking so long for you to do it I had to implement it in /users on my own which does more db operations that the rest of the site combined.

2. The connectivity that you did for schools was really redundant. For instance in schools, you just made a 3-4 line function and then did played copy and paste game. First you had this less work then you don't even do it properly is something that is not acceptable. And yeah the only insert operation that you did on site was - blogs that lacked basic validation (https://github.com/opengbu/gbuonline/blob/32cdcca8221de1023e97ba081a7872b0f9f70fb9/application/models/Blog_model.php)

3. Even this small work you did not complete. I had to to go and do lots of connectivity (compared to you specially) on the front end myself.

4. And the work that you did was very wrong, almost of all tables that you made I had to fix them. Then I had patch them here and also patch the front end. Sometimes I used to feel that it would been better if they did not exist in the first case.

> Yeah i get it you are the technical head so you think there is a need to boss around well let me tell you something as being the "Technical head" you should be giving us directions for our work, we are your team mates not your ___ slaves.

 ""directions for **our work**" - that is what I am trying to do. Work is something you (bhawesh) of all people should not speak off. Not only your work was little, you even failed to complete it. **I asked you several times to take some REAL work, but you always wanted to stick with the WORK that best suits your laziness**

>Things that should be removed
> you(Varun Garg) as the technical head

Alright, I am listening....so that's all the reason?
You think I am only one who is compaining? Your new partner sarthak used to say  same thing and used to tell me to give you content work since according to him you were doing nothing. When someone asks about your contribution he laughs about it. At least I do not believe in doing things such as behind someone's back. If I have issues I report them in front.  Even Amit Sir Asked me a few days ago ...**"kaun hai ye bhawesh, kuch kaam bhi karta hai vo"?**, and I was speechless with **kuch kaam**

> Team issues
> technical head's obsession and misuse of power .

Hmmm....That is coming from a guy who is almost removed from his "work" BECAUSE the work "existed" virtually. 

> and as for the above blank use your imagination.
> "You either die a hero or live long enough to see yourself become the villain"

I had the courtesy of asking you to do something and assigning you something, but you on the other hand can't control your emotions. If I did not knew you personally this would have happened a lot sooner. I knew sarthak but I did not expect such a reply from you at all.  Now that you have asked for it, I will wait to see the result and I have confidence on my dedication, so you are the one who should be afraid of the result.

I am dividing Technical team in 2 parts - Core and Extras. Extras will be you and Sarthak, and core will be rest. The extras will be a part of the team but not on GITHUB. They can submit their code using pull requests where it will be reviewed and then accepted. The reason you are not in the core is because to prevent you from entering core conversations which are only meant for those who do work. Also since your work will be like one pull request per month which is what guest collaborators do, it suits you best.

**Comment by Varun-garg** [comment]
> Dear "Technical head" the reason you are not seeing any work from my side is because its done(i think you should focus on your work rather than interfering with others) and when the team started everyone was assigned the work upon their interest and i did the same, So talking about everyone able to do the database work on their own, well guess what everyone is capable enough to do everyone else's work(even yours).

Dear Bhawesh, I remember correctly correctly you were given the task of handling databases on whole site. 

1. Though it was very small work, if you a bit serious about it, I wouldn't have been bothered at all. It was taking so long for you to do it I had to implement it in /users on my own which does more db operations that the rest of the site combined.

2. The connectivity that you did for schools was really redundant. For instance in schools, you just made a 3-4 line function and then did played copy and paste game. First you had this less work then you don't even do it properly is something that is not acceptable. And yeah the only insert operation that you did on site was - blogs that lacked basic validation (https://github.com/opengbu/gbuonline/blob/32cdcca8221de1023e97ba081a7872b0f9f70fb9/application/models/Blog_model.php)

3. Even this small work you did not complete. I had to to go and do lots of connectivity (compared to you specially) on the front end myself.

4. And the work that you did was very wrong, almost of all tables that you made I had to fix them. Then I had patch them here and also patch the front end. Sometimes I used to feel that it would been better if they did not exist in the first case.

> Yeah i get it you are the technical head so you think there is a need to boss around well let me tell you something as being the "Technical head" you should be giving us directions for our work, we are your team mates not your ___ slaves.

 ""directions for **our work**" - that is what I am trying to do. Work is something you (bhawesh) of all people should not speak off. Not only your work was little, you even failed to complete it. **I asked you several times to take some REAL work, but you always wanted to stick with the WORK that best suits your laziness**

>Things that should be removed
> you(Varun Garg) as the technical head

Alright, I am listening....so that's all the reason?
You think I am only one who is compaining? Your new partner sarthak used to say  same thing and used to tell me to give you content work since according to him you were doing nothing. When someone asks about your contribution he laughs about it. At least I do not believe in doing things such as behind someone's back. If I have issues I report them in front.  Even Amit Sir Asked me a few days ago ...**"kaun hai ye bhawesh, kuch kaam bhi karta hai vo"?**, and I was speechless with **kuch kaam**

> Team issues
> technical head's obsession and misuse of power .

Hmmm....That is coming from a guy who is almost removed from his "work" BECAUSE the work "existed" virtually. 

> and as for the above blank use your imagination.
> "You either die a hero or live long enough to see yourself become the villain"

I had the courtesy of asking you to do something and assigning you something, but you on the other hand can't control your emotions. If I did not knew you personally this would have happened a lot sooner. I knew sarthak but I did not expect such a reply from you at all.  Now that you have asked for it, I will wait to see the result and I have confidence on my dedication, so you are the one who should be afraid of the result.

I am dividing Technical team in 2 parts - Core and Extras. Extras will be you and Sarthak, and core will be rest. The extras will be a part of the team but not on GITHUB. They can submit their code using pull requests where it will be reviewed and then accepted. The reason you are not in the core is because to prevent you from entering core conversations which are only meant for those who do work. Also since your work will be like one pull request per month which is what guest collaborators do, it suits you best. 

## Alumni.

When alumni work was given, you told us that you are not interested in front end work and interested in connecting/creating the DBs, which you only did for listing the alumni profiles. On the other side I had to display whole profile on my own (with db), add/update/delete education info work info etc. The lists that you got had a "sorting ability", which was copy and paste of you code again and again with order by "thing". And then for distinguished you guys copied the same files (having the same content) and added distinguished status in query. Also Rishabh did code his events part on his own. Coincidentally gallery (under sarthak) was also lagging. Why is it every time I find something badly done, it is mostly under you two? I had too code things again for alumni, which involved me working overtime while you guys were not even bothered about the deadline . I was then asked about who did it and included everyone whose single line of code was present, which FYI excludes you both.
 
**Now the Technical head problem....**
This is the last time I am going to tell you and sarthak very clearly - most of the "powers" that I am given are only because I never asked for them. My only missions related to GBU Online are only learning new things and create a platform for this college. Because unlike the "negative elements" who only think about themselves, I can see the BIG PICTURE and I do realize that it will be a benefit for my career if my college's name goes UP. And also since I have finished a good deal of learning on this website one of my missions is already complete. Therefore I can be the "villain" or "die like a hero"  with no issues if and only if I see the site is being handled by capable team. gbuonline.in is a website that will never stop growing and not a school project where contributors will remain same to its grave .Long back when I was still managing the website without any official role, however Mr Sarthak did not accept my suggestions, So I quit the management process and became only focused on my work. Only then it came to be under focus that team must be brought under hierarchy.  This was also not my proposal, and being technical head was also not my plan. **I was not bringing this from the start because I knew it meant breaking some things for whoever is going to take the position.** However now I am accountable for the website and its development. But this allows me to take risks such as removing some positions and re assign some people who have poor quality of work.

You guys are only focused on getting new project. But when it comes to work you both want to finish it 1-2 hrs without caring about quality. On the other side -

**When good developers code something new, they always find 10 things missing. They try to do about 5 things at that time, do 3-4 things later and still regret not being able to do one thing, which they regret, and hope they will be able to finish.**  -Varun Garg

**Comment by Varun-garg** [comment]
> Dear "Technical head" the reason you are not seeing any work from my side is because its done(i think you should focus on your work rather than interfering with others) and when the team started everyone was assigned the work upon their interest and i did the same, So talking about everyone able to do the database work on their own, well guess what everyone is capable enough to do everyone else's work(even yours).

Dear Bhawesh, I remember correctly correctly you were given the task of handling databases on whole site. 
1. Though it was very small work, if you a bit serious about it, I wouldn't have been bothered at all. It was taking so long for you to do it I had to implement it in /users on my own which does more db operations that the rest of the site combined.
2. The connectivity that you did for schools was really redundant. For instance in schools, you just made a 3-4 line function and then did played copy and paste game. First you had this less work then you don't even do it properly is something that is not acceptable. And yeah the only insert operation that you did on site was - blogs that lacked basic validation (https://github.com/opengbu/gbuonline/blob/32cdcca8221de1023e97ba081a7872b0f9f70fb9/application/models/Blog_model.php)
3. Even this small work you did not complete. I had to to go and do lots of connectivity (compared to you specially) on the front end myself.
4. And the work that you did was very wrong, almost of all tables that you made I had to fix them. Then I had patch them here and also patch the front end. Sometimes I used to feel that it would been better if they did not exist in the first case.

> Yeah i get it you are the technical head so you think there is a need to boss around well let me tell you something as being the "Technical head" you should be giving us directions for our work, we are your team mates not your ___ slaves.

 ""directions for **our work**" - that is what I am trying to do. Work is something you (bhawesh) of all people should not speak off. Not only your work was little, you even failed to complete it. **I asked you several times to take some REAL work, but you always wanted to stick with the WORK that best suits your laziness**

> Things that should be removed
> you(Varun Garg) as the technical head

Alright, I am listening....so that's all the reason?
You think I am only one who is compaining? Your new partner sarthak used to say  same thing and used to tell me to give you content work since according to him you were doing nothing. When someone asks about your contribution he laughs about it. At least I do not believe in doing things such as stabbing behind someone's back. If I have issues I report them in front.  Even Amit Sir Asked me a few days ago ...**"kaun hai ye bhawesh, kuch kaam bhi karta hai vo"?**, and I was speechless with **kuch kaam**

> Team issues
> technical head's obsession and misuse of power .

Hmmm....That is coming from a guy who is almost removed from his "work" BECAUSE the work "existed" virtually. 

> and as for the above blank use your imagination.
> "You either die a hero or live long enough to see yourself become the villain"

I had the courtesy of asking you to do something and assigning you something, but you on the other hand can't control your emotions. If I did not knew you personally this would have happened a lot sooner. I knew sarthak but I did not expect such a reply from you at all.  Now that you have asked for it, I will wait to see the result and I have confidence on my dedication, so you are the one who should be afraid of the result.

I am dividing Technical team in 2 parts - Core and Extras. Extras will be you and Sarthak, and core will be rest. The extras will be a part of the team but not on GITHUB. They can submit their code using pull requests where it will be reviewed and then accepted. The reason you are not in the core is because to prevent you from entering core conversations which are only meant for those who do work. Also since your work will be like one pull request per month which is what guest collaborators do, it suits you best. 

## Alumni.

When alumni work was given, you told us that you are not interested in front end work and interested in connecting/creating the DBs, which you only did for listing the alumni profiles. On the other side I had to display whole profile on my own (with db), add/update/delete education info work info etc. The lists that you got had a "sorting ability", which was copy and paste of you code again and again with order by "thing". And then for distinguished you guys copied the same files (having the same content) and added distinguished status in query. Also Rishabh did code his events part on his own. Coincidentally gallery (under sarthak) was also lagging. Why is it every time I find something badly done, it is mostly under you two? I had to code things again for alumni, which involved me working overtime while you guys were not even bothered about the deadline . I was then asked about who did it and included everyone whose single line of code was present, which FYI excludes you both.

**Now the Technical head problem....**
This is the last time I am going to tell you and sarthak very clearly - most of the "powers" that I am given are only because I never asked for them. My only missions related to GBU Online are only learning new things and create a platform for this college. Because unlike the "negative elements" who only think about themselves, I can see the BIG PICTURE and I do realize that it will be a benefit for my career if my college's name goes UP. And also since I have finished a good deal of learning on this website one of my missions is already complete. Therefore I can be the "villain" or "die like a hero"  with no issues if and only if I see the site is being handled by capable team. gbuonline.in is a website that will never stop growing and not a school project where contributors will remain same to its grave .Long back when I was still managing the website without any official role, however Mr Sarthak did not accept my suggestions, So I quit the management process and became only focused on my work. Only then it came to be under focus that team must be brought under hierarchy.  This was also not my proposal, and being technical head was also not my plan. **I was not bringing this from the start because I knew it meant breaking some things for whoever is going to take the position.** However now I am accountable for the website and its development. But this allows me to take risks such as removing some positions and re assign some people who have poor quality of work.

**You guys are only focused on getting new project. But when it comes to work you both want to finish it 1-2 hrs without caring about quality.** On the other side -

**When good developers code something new, they always find 10 things missing. They try to do about 5 things at that time, do 3-4 things later and still regret not being able to do one thing,  and hope they will be able to finish very soon.**  -Varun Garg

**Comment by Varun-garg** [comment]
Finally, @gargsarthak30, replying about some of the points

>   You never asked me to change the navbar. I don't know why you have pointed out this thing which actually never happened.

https://github.com/opengbu/gbuonline/issues/8

>    Coming on to the exams part, you yourself said to upload the papers on google drive so as to lower down the load at server, and then when I updated accordingly you tell us to put it on our server itself. (If you don't believe on this you may ask Rajat about this thing.)

I told you before doing it ask Amit Sir, which you said he would agree and proceeded. And that " server load" thing was your way of trying to convince me, and since you were so eager about it, I could not stop you
  
>  Backdoor access : Man, Three of us (Me , Bhawesh and Rajat) had made changes to the contributors page, but we didn't added authentication part just because you were actually responsible for that thing. We even came to your room thrice , but unfortunately your room was found locked, we called you but you cared enough of picking up the call. I have never asked for any backdoor access , never been fond of "POWERS" like you. Working just to enhance my skills and learn something.

Well, that were some skills. When discussed later, you said without this content head could have gotten anyone on the contributors list. So you wanted to applied this code so that anyone who was made a writer by him had to be verified by "us". The only difference when I posted this back and now is only that earlier anyone could do your "verification" process and now it is in hands of technical team. In **both** cases this definitely voids the authority of content head to an extent, which was my main point. Perhaps you should read again what I said before. 



> One last thing, If you are working in a team then please have the etiquettes to talk directly to that person first rather than making an issue and posting it. 

One thing that I have realized with working with you is that everything that I must say to you must go through a public channel.

**Comment by Varun-garg** [comment]
Finally, @gargsarthak30, replying about some of the points

>   You never asked me to change the navbar. I don't know why you have pointed out this thing which actually never happened.

https://github.com/opengbu/gbuonline/issues/8

>    Coming on to the exams part, you yourself said to upload the papers on google drive so as to lower down the load at server, and then when I updated accordingly you tell us to put it on our server itself. (If you don't believe on this you may ask Rajat about this thing.)

I told you before doing it ask Amit Sir, which you said he would agree and proceeded. And that " server load" thing was your way of trying to convince me, and since you were so eager about it, I could not stop you

>  Backdoor access : Man, Three of us (Me , Bhawesh and Rajat) had made changes to the contributors page, but we didn't added authentication part just because you were actually responsible for that thing. We even came to your room thrice , but unfortunately your room was found locked, we called you but you cared enough of picking up the call. I have never asked for any backdoor access , never been fond of "POWERS" like you. Working just to enhance my skills and learn something.

Well, that were some skills. When discussed later, you said without this content head could have gotten anyone on the contributors list. So you wanted to apply this code so that anyone who was made a writer by him had to be verified by "us". The only difference when I posted this back and now is only that earlier anyone could do your "verification" process and now it is in hands of technical team. In **both** cases this definitely voids the authority of content head to an extent, which was my main point. Perhaps you should read again what I said before. 

> One last thing, If you are working in a team then please have the etiquettes to talk directly to that person first rather than making an issue and posting it. 

One thing that I have realized while working with you is that everything that I must say to you must go through a public channel.

**Comment by Varun-garg** [comment]
Another thing that must be added - newsletters

**Comment by rajatsaxena035** [comment]
@Varun-garg  good idea.....

More Proposals:
- Rating points for every user (Amit Sir's idea).
- Questionnaire - Question of the Day - The users who answer it will get rating points.
- Image Gallery (Any one can upload images, but it will be published only after approval, like blogs). The best image will be on the slider with the credits to the person who uploaded it.
- Video Gallery (for Abhivyanjana, Shouryotsav, Teachers Day, Freshers, Farewell, other events)
- A special section to recognize the BEST in GBU : 
  Eg:
  Best Musician
  Best Orator
  Best Teacher
  Best Sportperson
  Best Dancer
  etc
  This section could be quite attractive for users.

**Comment by Varun-garg** [comment]
Work plan up to 28th october 2015 (Dead Line)

### Kshitij Purwar
1. Girls hostel info.
2. Upload Exam papers.
3. Warden list.
4. Mess Menu.

### Bhawesh Chandola
1. Single, interactive interface for academic calendar and list of holidays. 
2. Database for the above.
3. Data for the above.

### Sarthak Garg
1. Ebooks.
2. Placements.
3. Opportunities.
4. Clubs.
5. Student Chapters.

### Shobhit Sharma
Hostel Management System-
1. Hostels vnb notice link from db, (right now it is same for all notices as the column was not created)
2. Fix room change request.
3. Specific - fix dropdown.
4. Specific - hostel notice, allocation lists and mess menu should be acc. to hostel selected.
5. Mess menu - Most hostels have their own menu, so we can not have single menu.

### Rajat Saxena
1. Schools - link course structure and faculty info with their own tables.
2. blogs - Rating
3. Notices
4. Events
5. Contributors - Writers according to rating and team list from github list of contributors
 
### Rishabh Ahuja
1. Exams
2. SEO
3. Feedback
4. TOU 
5. Vision

### Varun Garg
1. Front Page
    1. Design - more simple, sharp and attractive
    2. Looks dynamic
    3. Mix news with news from gbu.ac.in using js 
    4. Do this for maximum things possible.
2. Users
    1. Newsletters
    2. create a interface for wardens,
    3. Drag and drop upload for all sections
    4. Rating System on /users side
    5. Display feedback, etc

**Note :** None of this work is assigned to a user permanently.  Please try to complete this by 28th October. On 29th all this will be re evaluated and the weak sections will be assigned to person with better work.  (This does not apply to Kshittij)

**Comment by Varun-garg** [comment]
Work plan up to 28th october 2015 **(Dead Line)**

### Kshitij Purwar
1. Girls hostel info.
2. Upload Exam papers.
3. Warden list.
4. Mess Menu.

### Bhawesh Chandola
1. Single, interactive interface for academic calendar and list of holidays. 
2. Database for the above.
3. Data for the above.

### Sarthak Garg
1. Ebooks.
2. Placements.
3. Opportunities.
4. Clubs.
5. Student Chapters.

### Shobhit Sharma
Hostel Management System-
1. Hostels vnb notice link from db, (right now it is same for all notices as the column was not created)
2. Fix room change request.
3. Specific - fix dropdown.
4. Specific - hostel notice, allocation lists and mess menu should be acc. to hostel selected.
5. Mess menu - Most hostels have their own menu, so we can not have single menu.

### Rajat Saxena
1. Schools - link course structure and faculty info with their own tables.
2. blogs - Rating
3. Notices
4. Events
5. Contributors - Writers according to rating and team list from github list of contributors
 
### Rishabh Ahuja
1. Exams
2. SEO
3. Feedback
4. TOU 
5. Vision

### Varun Garg
1. Front Page
    1. Design - more simple, sharp and attractive
    2. Looks dynamic
    3. Mix news with news from gbu.ac.in using js 
    4. Do this for maximum things possible.
2. Users
    1. Newsletters
    2. create a interface for wardens,
    3. Drag and drop upload for all sections
    4. Rating System on /users side
    5. Display feedback, etc

**Note :** None of this work is assigned to a user permanently.  Please try to complete this by 28th October. On 29th all this will be re evaluated and the weak sections will be assigned to person with better work.  (This does not apply to Kshittij)

**Comment by Varun-garg** [comment]
Work plan up to 28th october 2015 **(Deadline)**

### Kshitij Purwar
1. Girls hostel info.
2. Upload Exam papers.
3. Warden list.
4. Mess Menu.

### Bhawesh Chandola
1. Single, interactive interface for academic calendar and list of holidays. 
2. Database for the above.
3. Data for the above.

### Sarthak Garg
1. Ebooks.
2. Placements.
3. Opportunities.
4. Clubs.
5. Student Chapters.

### Shobhit Sharma

Hostel Management System-
1. Hostels vnb notice link from db, (right now it is same for all notices as the column was not created)
2. Fix room change request.
3. Specific - fix dropdown.
4. Specific - hostel notice, allocation lists and mess menu should be acc. to hostel selected.
5. Mess menu - Most hostels have their own menu, so we can not have single menu.

### Rajat Saxena
1. Schools - link course structure and faculty info with their own tables.
2. blogs - Rating
3. Notices
4. Events
5. Contributors - Writers according to rating and team list from github list of contributors

### Rishabh Ahuja
1. Exams
2. SEO
3. Feedback
4. TOU 
5. Vision

### Varun Garg
1. Front Page
   1. Design - more simple, sharp and attractive
   2. Looks dynamic
   3. Mix news with news from gbu.ac.in using js 
   4. Do this for maximum things possible.
2. Users
   1. Newsletters
   2. create a interface for wardens,
   3. Drag and drop upload for all sections
   4. Rating System on /users side
   5. Display feedback, etc

**Note :** None of this work is assigned to a user permanently.  Please try to complete this by 28th October. On 29th all this will be re evaluated and the weak sections will be assigned to person with better work.  (This does not apply to Kshittij)

**Comment by gargsarthak30** [comment]
Amit Sir has asked me to create an app for the exam papers. So it is possible that I might start my work on app after some time, therefore I need to structure the Exam section accordingly. So, I request you to give me the exam section and Rishabh can be given some other page from my set.

**Comment by Varun-garg** [comment]
@gargsarthak30 No offense, but the exams section that was previously under you was a bit difficult to navigate. You can use this section or create another section that fits your needs, which will be useful for your application. For internal structure, I am already changing it according to sir, so I am afraid it can't be given to you right now, but your suggestions are welcome.
