### ISSUE TITLE
Web Development Workshop

### ISSUE THREAD

**Issue by rajatsaxena035** [opengbu/gbuonline#33]
As discussed earlier in the last team meeting, we are going to organize a "_Web Development Workshop_". The _event details_ are as follows:
1. **Event Date** : 31-Oct to 6-Nov
2. **Audience** : 1st and 2nd year students ONLY.
3. **Work Distribution** :  [GitHub Wiki](https://github.com/opengbu/gbuonline/wiki/Web-Development-Workshop-Distribution)
4. **Event Schedule** : [GitHub Wiki](https://github.com/opengbu/gbuonline/wiki/Web-Development-Workshop-Distribution)
5. **Event Venue** : SOVSAS 
6. Anyone having problem with the Distribution or Schedule, please sort them till Friday (16 Oct).
7. If you are fine with the Distribution or Schedule, then please comment "OK" in this issue thread.

**Comment by rajatsaxena035** [comment]
Schedule has been updated.
Please see the updated one at : [GitHub Wiki](https://github.com/opengbu/gbuonline/wiki/Web-Development-Workshop-Distribution)

**Comment by Varun-garg** [comment]
Good plan.

**Comment by rajatsaxena035** [comment]
Schedule updated yet again. (incorporated suggestions from Shobhit, Sarthak and Varun).
See Here : [GitHub Wiki](https://github.com/opengbu/gbuonline/wiki/Web-Development-Workshop-Distribution)

**Comment by rajatsaxena035** [comment]
Drastic change in Schedule.
Please inform Vasudev for the same.
See Here : [GitHub Wiki](https://github.com/opengbu/gbuonline/wiki/Web-Development-Workshop-Distribution)

**Comment by rajatsaxena035** [comment]
Due to time constraints, Schedule has been updated.
See Here : [GitHub Wiki](https://github.com/opengbu/gbuonline/wiki/Web-Development-Workshop-Distribution)

**Comment by rajatsaxena035** [comment]
Schedule has been updated.
See Here : [GitHub Wiki](https://github.com/opengbu/gbuonline/wiki/Web-Development-Workshop-Distribution)

**Comment by rajatsaxena035** [comment]
Updated Schedule
See Here : [GitHub Wiki](https://github.com/opengbu/gbuonline/wiki/Web-Development-Workshop-Distribution)

**Comment by rajatsaxena035** [comment]
Serious changes in [Schedule](https://github.com/opengbu/gbuonline/wiki/Web-Development-Workshop-Distribution).
Please specify the suggestions regarding it.

**Comment by rajatsaxena035** [comment]
There are some concerns regarding the Workshop Schedule.
Lets have a team meeting tomorrow after the Practical Exam.

**Comment by rajatsaxena035** [comment]
Although I have updated the [Schedule](https://github.com/opengbu/gbuonline/wiki/Web-Development-Workshop-Distribution), I doubt that we will be able to get permissions regarding classes because "_Back-Papers_" are till **12-Dec**. And they don't even allow us to enter the school premises in the exam time.
Any suggestions ??

**Comment by rajatsaxena035** [comment]
9-Dec [Schedule](https://github.com/opengbu/gbuonline/wiki/Web-Development-Workshop-Distribution)
