### ISSUE TITLE
content writers images broken in contributors page

### ISSUE THREAD

**Issue by Varun-garg** [opengbu/gbuonline#39]
I was just browsing the website when I saw that images of content writers is broken. I think that error occurred when someone who mdified the contributors page decided to add default image for users who did not have their images. He set default path to image and uploaded it to our cdn, and hence changed moved image link in content writers page to cdn. Good idea but the images uploaded by users now also trying to load them from there. Alternate working idea could have been simply checking if the image links are empty and then loading default image from CDN....

**Comment by rajatsaxena035** [comment]
Fixed
