### ISSUE TITLE
Content work

### ISSUE THREAD

**Issue by bhaweshchandola** [opengbu/gbuonline#4]
As varun mentioned we should probably bring rishabh along and give him the content work of the site.. thoughts? If you all agree i'll talk to him. Reply asap.

**Comment by Varun-garg** [comment]
Only if we all agree, Rishabh will be asked to do this. If he doesent we will give a chance to anyone who wants to do it . If we dont then this job be split b/w us.

**Comment by bhaweshchandola** [comment]
yeah varun is ryt. so plz reply asap.

**Comment by rajatsaxena035** [comment]
Before talking to Rishabh, we should first make a list of all the "Content Work" required .
1. Schools
2. Clubs
3. Hostels
4. Notices
Please continue the list.....

**Comment by Varun-garg** [comment]
Few events, blogs.
