### ISSUE TITLE
General Discussion

### ISSUE THREAD

**Issue by Varun-garg** [opengbu/gbuonline#5]
This is not a issue but a general discussion thread.

For a start , by going here https://github.com/orgs/opengbu/people and changing your status to public will let all people see that you are member of this orgaization. I enabled this because this also lists the commits that I made in my profile.

**Comment by Varun-garg** [comment]
For anyone having issues using github tools, check out https://github.com/opengbu/gbuonline/wiki/connecting-to-github-using-netbeans-instead-of-github-app

**Comment by Varun-garg** [comment]
I have changes background image and no-repeat to repeat [Preview](http://tech-league.me/)  . You guys can revert if it doesent fit.

**Comment by Varun-garg** [comment]
Please drop tables and import gbuonline.sql again.

**Comment by Varun-garg** [comment]
IMPORTANT Database Update. please refresh all tables

**Comment by Varun-garg** [comment]
As on bootstrap page, on devices not using responsive design ... it can be manually triggered by adding this meta tag in head

```
<meta name="viewport" content="width=device-width, initial-scale=1.0">
```

I have already added it in users section but due to unfinished work, I am not commiting it. Someone in meanwhile can add it in front end.

**Comment by kshitijpurwar** [comment]
hey , got some design solutions for front end:
http://paletton.com/#uid=1000u0kllllaFw0g0qFqFg0w0aF(google color pallete for more),
http://uigradients.com/#,
http://subtlepatterns.com/

**Comment by rajatsaxena035** [comment]
Thanks @kshitijpurwar .

**Comment by Varun-garg** [comment]
Front end is not in my hand, and other members are not listening to me in making a more dynamic and more better designed website (and NOT allowing me to change the most weak parts). **I cant see all my hard work go waste** because someone saying only he has right to edit front page. I have to create a new project. https://github.com/Varun-garg/edu_cms . It will be a full fledged cms with a lot better UI, completely dynamic and customizable. I will only be using the files which I wrote fully on my own (/users directory). I will keep contributing to main site (user/admin panel **only** from now on) as much as it's needed.

**Comment by Varun-garg** [comment]
New files uploaded on site, and technological updates issue on front page resolved.

**Comment by Varun-garg** [comment]
I have moved user upload related files out of resources directory. and uploaded a patch to do this on gbuonline.in and updates all the possible references in database. No data was lost. Now resources directory can be overwritten if needed.

**Comment by rajatsaxena035** [comment]
good move.

**Comment by Varun-garg** [comment]
I am deleting user1 and student1 accounts as detailed logs are now working. From now on whoever needs the test accounts should create them on his own.

 Anyone who has shared his password, should now change it, because if anything goes wrong his account will be displayed in them.

**Comment by Varun-garg** [comment]
@kshitijpurwar, You can not remove our previous content writers Vasudev Yadav and Apurva, just because you have not met them. Compared to the new content writers, they have also done good amount of work. Contact them and if you still have issues then do anything you want.

**Comment by kshitijpurwar** [comment]
## Issues on the front end:
1. The background image is not being displayed and let the content team decide the appearance of the site.
2. The font used in the footer should be _larger_ and quick links bigger and circular.
3. For the quote ,use a handwritten quote and larger font here too.
4. The footer should show last updated like it used to.
5. Make use of the full space available on the homepage.Don't leave empty spaces(looks bad).
   My team will decide the fonts to be use and **color** pallete too .Hope you can make the changes accordingly.

## Back End issues:
1. I can't see the stats and logs.
2. Remove upload media option and instead of it ,make available the option to upload the images at the respective place.

**Comment by gargsarthak30** [comment]
The background image is already being displayed and I think everyone in the team is pretty much happy with the background. If you have some other background send us the link , we'll update it if everyone likes it.
Coming on to the quotes part, the quotes have been changed now. As soon as the site gets updated you'll see much better quotes.
And can you specify a little ,where do you actually see empty spaces ?

**Comment by Varun-garg** [comment]
@kshitijpurwar Since you have ignored my last message (still not meet vasudev and apurva), they are not going to be removed for now. Also they are **founder** members just like technical team. They were not assigned by you in the first case. To remove them you need to get permission of Amit Sir. 

The statistics page will be made accessible to you. However, the logs section is to troubleshoot any technical/security issues and has no relation with content on site, so It can not be displayed.

For separate upload in each section, yes I will do it, but when I see **some real content**. And this also goes for some front end issues that you have, You cant just keep complaining and doing next to nothing. For instance mid sems are over and no new papers are uploaded, no blogs, events etc. How can our site run without efficient content? Development/Maintenance is a never ending cycle and there will always be something new for us to implement.  Our site can have more than one content managers, And team is considering of having separate head from each year to do the job. It is not my idea, but with your dedication towards this I don't think anyone will disagree. 
We welcome your/anyone's suggestions and this has nothing to do with them.

**Comment by kshitijpurwar** [comment]
Hey I am unable to upload any media on site using the media upload.Someone please look into it.

**Comment by rajatsaxena035** [comment]
I have moved all the pages linked in footer from "pages" folder to sub-folder "footer_pages" in Views.
Accordingly, I have changed the URLs in controllers.
Please check your respective pages and url, if any error occurs.

**Comment by awasthi** [comment]
Varun, As I am reading your discussion, I think each developer should be independent of each other. 
As Sarthak wants to add some fields and he depends on admin. In my opinion it would be much better if if should be able to do this task himself. Then we say our developement is modular. Think over it.

**Comment by Varun-garg** [comment]
@awasthi, sir, it is a good idea. The code of users section has increased a lot and will become difficult to manage by 1 person in upcoming days. Many sections - schools, blogs, exams, events, hostels etc can be handled by the person assigned to them. Things that must be taken care of are logs, permissions, security and no redundancy. For logs and permissions the existing models must be used and for the rest existing code can be referred. Though it is my work to handle it, anyone is welcome to change it (like shobhit added stats page), and if anyone changes/adds some fields and it makes it malfunction, he is recommended to do apply the same changes here too.

**Comment by Varun-garg** [comment]
Good news, There is a 5th year student (Civil Engineering) with all exam papers of his batch. He is going to upload all of them

**Comment by rajatsaxena035** [comment]
@Varun-garg 
According to the current structure, there can only be  5 upcoming events.
And all of the 5 slots have been occupied.
Therefore, please change this structure in the admin panel and don't put any limitation on the number of upcoming events. 
Also check the "Event Date". It resets to the current date when editing an event. 
Please do it as soon as possible because huge no. of events are being organised in GBU (in this week).
