### ISSUE TITLE
link.php to container-fluid or container-fuid?

### ISSUE THREAD

**Issue by Varun-garg** [opengbu/gbuonline#7]
Though I fixed slider and footer(with some other changes) to prevent page width to exceed the browser width somepages still had same issue ,  I found that in link.php container-fluid was spelled wrong as container-fuid causing many of these issues. When I corrected typo, everything became good except that now footer backgound and header background also have margins.

**Comment by rajatsaxena035** [comment]
@Varun-garg  <br>I have fixed this issue. A certain div was creating all the problem and have also changed the controllers such that the page heading in the red bkgrnd comes from respective controllers and not from views. But<b> I have not commited </b>it to the master branch as bhawesh is currently using the controller files for DB connectivity.

**Comment by Varun-garg** [comment]
You can really commit the changes, Only the changes which bhawesh makes will be reflected when he upldates it, because before he commits them he will be notified his branch is behind and will have to update his code. Then only changes that you did will be done in his code (not replacing it completely).
