### ISSUE TITLE
Images

### ISSUE THREAD

**Issue by awasthi** [opengbu/gbuonline#8]
Size of images is a minor issue. At my screen images are appearing in stretched form. So one thing is  images should be cropped in size. So discuss and fix different template of images (size). Also think about some code for auto adjustment of images according to system resolution.

**Comment by awasthi** [comment]
CSS Compatibility issue. Text visibility has gone!
![p1](https://cloud.githubusercontent.com/assets/124547/8506646/35bd7dee-223d-11e5-9ba3-2b1c3f3da8c1.PNG)

**Comment by Varun-garg** [comment]
Even if we change padding deppeding upon page width, it would fi text visiblity and not fix nabar spitting in 2 on smaller screens such as desktop monitors (not small as mobile). I suggest
1. Convert Text GBU Online into our site icon (with navbar theme) to save some space.
2. Merge Acadminc calander, notice board and exams into one dropdown (like more)

**Comment by gargsarthak30** [comment]
Our navbar works perfectly for default screen size. If we change our screen
size from 100% to some other value then only it splits. And most of the
people have their screen set to default size, So I don't think we should
change it.

**Comment by Varun-garg** [comment]
By default screen size you mean default screen size of 15.6 inch laptops. If you still dont get it go to http://www.webestools.com/resolution-tester-screen-size-page-design-test-screen-resolution-website-online-display.html and see it yourself. Even on 1024x768 screen our navbar fails miserably. Not only splits in 2-3 parts, it also hides the main content. It is damn overcrouded with least important things. Intrestingly it misses stuff like blogs on which we are planning to be a big part of site

![screenshot from 2015-07-05 18-03-09](https://cloud.githubusercontent.com/assets/5960246/8511652/9719f1dc-2312-11e5-8a8d-360ed60b1af1.png)

**Comment by gargsarthak30** [comment]
I wasn't talking of screen size in terms of inches.
Anyways i'll change the navbar contents and try to make it better. Give me one or two days and ill post it. Moreover the e-books section is also almost ready so Rajat or I will upload it in one or two days.

-----Original Message-----

**Comment by Varun-garg** [comment]
Then in terms of what you were talking about?

>  If we change our screen size from 100% to some other value then only it splits. 

Only happens with bg screen -> good resolution laptops.

**Comment by gargsarthak30** [comment]
In terms of resolution.
Anyways I'll change it. 
Matter closed!

-----Original Message-----

**Comment by Varun-garg** [comment]
Man, By 15.6 inch good resolution is understood. It was just an example (mainly regarding your case) . Of course I was talking about resolution, my whole post spoke about resolution.By saying that you just pissed me off. Your level of smartness never fails to amaze me.

**Comment by gargsarthak30** [comment]
Varun this matter was just about the navbar.
I can't understand why you are just stretching this topic unnecessarily. I was saying some other thing and it seems like you are busy arguing over some idiotic thing. I am not here to compare laptops.
P.S: Rather than replying here again and again you may call me if you dont understand what I wanted to say!

-----Original Message-----

**Comment by Varun-garg** [comment]
Someone has asked for proof of this conversation. Though this much should be enough to remind him, the last 2 messages of this issue were removed earlier. I am restoring them just so that he can remember it... (https://github.com/opengbu/gbuonline/issues/8)

> ---------- Forwarded message ----------
> From: Varun Garg notifications@github.com
> Date: Sun, Jul 5, 2015 at 7:15 PM
> Subject: Re: [gbuonline] Images (#8)
> To: opengbu/gbuonline gbuonline@noreply.github.com
> 
> Man, By 15.6 inch good resolution is understood. It was just an example (mainly regarding your case) . Of course I was talking about resolution, my whole post spoke about resolution.By saying that you just pissed me off. Your level of smartness never fails to amaze me.
> 
> ---------- Forwarded message ----------
> From: Sarthak Garg notifications@github.com
> Date: Sun, Jul 5, 2015 at 8:24 PM
> Subject: Re: [gbuonline] Images (#8)
> To: opengbu/gbuonline gbuonline@noreply.github.com
> 
> Varun this matter was just about the navbar.
> I can't understand why you are just stretching this topic unnecessarily. I was saying some other thing and it seems like you are busy arguing over some idiotic thing. I am not here to compare laptops.
> P.S: Rather than replying here again and again you may call me if you dont understand what I wanted to say!
